// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-driver-location.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-driver-location.ts
var get_driver_location_default = defineTool({
  name: "get_driver_location",
  title: "\xDAltima ubicaci\xF3n del conductor",
  description: "Devuelve la \xFAltima posici\xF3n GPS registrada del conductor de un viaje.",
  inputSchema: {
    trip_id: z.string().uuid().describe("Identificador UUID del viaje.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("driver_locations").select("latitude, longitude, heading, speed, accuracy, created_at").eq("trip_id", trip_id).order("created_at", { ascending: false }).limit(1);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: `Sin ubicaciones para el viaje ${trip_id}.` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { location: data[0] }
    };
  }
});

// src/lib/mcp/tools/get-driver-position-history.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_driver_position_history_default = defineTool2({
  name: "get_driver_position_history",
  title: "Hist\xF3rico de posiciones del conductor",
  description: "Devuelve el hist\xF3rico reciente de posiciones GPS de un viaje, de m\xE1s nueva a m\xE1s antigua.",
  inputSchema: {
    trip_id: z2.string().uuid().describe("Identificador UUID del viaje."),
    limit: z2.number().int().min(1).max(200).default(30).describe("N\xFAmero m\xE1ximo de posiciones a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("driver_locations").select("latitude, longitude, created_at").eq("trip_id", trip_id).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { positions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/calculate-trip-price.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/priceCalculator.ts
var FUEL_COST_PER_KM = 0.17;
var MAINTENANCE_PER_KM = 0.1;
var TOTAL_COST_PER_KM = FUEL_COST_PER_KM + MAINTENANCE_PER_KM;
var COMMISSION = 0.12;
var OCCUPANCY_FACTORS = {
  1: 1.8,
  2: 2.5,
  3: 3.8,
  4: 4.5
};
var TRAFFIC_MULTIPLIER = {
  normal: 1,
  moderate: 1.15,
  rush: 1.3
};
function calculatePrice({
  distanceKm,
  passengerCount,
  detourKm = 0,
  traffic = "normal"
}) {
  const factor = OCCUPANCY_FACTORS[passengerCount] ?? OCCUPANCY_FACTORS[1];
  const trafficMultiplier = TRAFFIC_MULTIPLIER[traffic];
  const totalCost = distanceKm * TOTAL_COST_PER_KM;
  const detourSurcharge = detourKm * TOTAL_COST_PER_KM;
  const basePrice = (totalCost / factor + detourSurcharge) * trafficMultiplier;
  const passengerPrice = basePrice * (1 + COMMISSION);
  const commissionAmount = passengerPrice - basePrice;
  const driverIncome = basePrice;
  const driverTotalIncome = basePrice * passengerCount;
  return {
    totalCost: round2(totalCost),
    basePrice: round2(basePrice),
    passengerPrice: round2(passengerPrice),
    driverIncome: round2(driverIncome),
    driverTotalIncome: round2(driverTotalIncome),
    commissionAmount: round2(commissionAmount),
    detourSurcharge: round2(detourSurcharge),
    trafficMultiplier
  };
}
function round2(n) {
  return Math.round(n * 100) / 100;
}

// src/lib/mcp/tools/calculate-trip-price.ts
var calculate_trip_price_default = defineTool3({
  name: "calculate_trip_price",
  title: "Calcular compensaci\xF3n por compartir gastos",
  description: "Calcula la compensaci\xF3n por compartir gastos de un trayecto con la f\xF3rmula de VIMATCH (coste por km, factor de ocupaci\xF3n, desv\xEDo, tr\xE1fico y comisi\xF3n).",
  inputSchema: {
    distance_km: z3.number().positive().describe("Distancia del trayecto en kil\xF3metros."),
    passenger_count: z3.union([z3.literal(1), z3.literal(2), z3.literal(3), z3.literal(4)]).describe("N\xFAmero de pasajeros (1-4)."),
    detour_km: z3.number().min(0).default(0).describe("Kil\xF3metros extra de desv\xEDo del conductor."),
    traffic: z3.enum(["normal", "moderate", "rush"]).default("normal").describe("Factor de tr\xE1fico: normal, moderate u hora punta (rush).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ distance_km, passenger_count, detour_km, traffic }) => {
    const breakdown = calculatePrice({
      distanceKm: distance_km,
      passengerCount: passenger_count,
      detourKm: detour_km ?? 0,
      traffic: traffic ?? "normal"
    });
    return {
      content: [{ type: "text", text: JSON.stringify(breakdown) }],
      structuredContent: { breakdown }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kjfxkyhwghtlawobbukq";
var mcp_default = defineMcp({
  name: "vimatch",
  title: "VIMATCH",
  version: "0.1.0",
  instructions: "Herramientas de VIMATCH, la app de viajes compartidos en trayectos diarios. Consulta la ubicaci\xF3n y el hist\xF3rico GPS de un viaje y calcula la compensaci\xF3n por compartir gastos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_driver_location_default, get_driver_position_history_default, calculate_trip_price_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
